export const FETCH_FIREBASE_ITEMS_SUCCESS = 'FETCH_FIREBASE_ITEMS_SUCCESS';
export const FETCH_FIREBASE_ITEMS_FAILURE = 'FETCH_FIREBASE_ITEMS_FAILURE';

export const FETCH_FIREBASE_USER_ITEMS_SUCCESS = 'FETCH_FIREBASE_USER_ITEMS_SUCCESS';
export const FETCH_FIREBASE_USER_ITEMS_FAILURE = 'FETCH_FIREBASE_USER_ITEMS_FAILURE';

export const CREATE_FIREBASE_USER_ITEM_SUCCESS = 'CREATE_FIREBASE_USER_ITEM_SUCCESS';
export const CREATE_FIREBASE_USER_ITEM_FAILURE = 'CREATE_FIREBASE_USER_ITEM_FAILURE';

export const UPDATE_FIREBASE_USER_ITEM_SUCCESS = 'UPDATE_FIREBASE_USER_ITEM_SUCCESS';
export const UPDATE_FIREBASE_USER_ITEM_FAILURE = 'UPDATE_FIREBASE_USER_ITEM_FAILURE';

export const DELETE_FIREBASE_USER_ITEM_SUCCESS = 'DELETE_FIREBASE_USER_ITEM_SUCCESS';
export const DELETE_FIREBASE_USER_ITEM_FAILURE = 'DELETE_FIREBASE_USER_ITEM_FAILURE';