export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';

export const FETCH_USER_ITEMS_SUCCESS = 'FETCH_USER_ITEMS_SUCCESS';
export const FETCH_USER_ITEMS_FAILURE = 'FETCH_USER_ITEMS_FAILURE';

export const CREATE_USER_ITEM_SUCCESS = 'CREATE_USER_ITEM_SUCCESS';
export const CREATE_USER_ITEM_FAILURE = 'CREATE_USER_ITEM_FAILURE';

export const UPDATE_USER_ITEM_SUCCESS = 'UPDATE_USER_ITEM_SUCCESS';
export const UPDATE_USER_ITEM_FAILURE = 'UPDATE_USER_ITEM_FAILURE';

export const DELETE_USER_ITEM_SUCCESS = 'DELETE_USER_ITEM_SUCCESS';
export const DELETE_USER_ITEM_FAILURE = 'DELETE_USER_ITEM_FAILURE';
