export const FETCH_ADS_SUCCESS = 'FETCH_ADS_SUCCESS';
export const FETCH_ADS_FAILURE = 'FETCH_ADS_FAILURE';

export const FETCH_USER_ADS_SUCCESS = 'FETCH_USER_ADS_SUCCESS';
export const FETCH_USER_ADS_FAILURE = 'FETCH_USER_ADS_FAILURE';

export const CREATE_USER_AD_SUCCESS = 'CREATE_USER_AD_SUCCESS';
export const CREATE_USER_AD_FAILURE = 'CREATE_USER_AD_FAILURE';

export const UPDATE_USER_AD_SUCCESS = 'UPDATE_USER_AD_SUCCESS';
export const UPDATE_USER_AD_FAILURE = 'UPDATE_USER_AD_FAILURE';

export const DELETE_USER_AD_SUCCESS = 'DELETE_USER_AD_SUCCESS';
export const DELETE_USER_AD_FAILURE = 'DELETE_USER_AD_FAILURE';

export const CLEAR_USER_ADS = 'CLEAR_USER_ADS';
