export const FETCH_FIREBASE_USER_SUCCESS = 'FETCH_FIREBASE_USER_SUCCESS';
export const FETCH_FIREBASE_USER_FAILURE = 'FETCH_FIREBASE_USER_FAILURE';

export const LOGOUT_FIREBASE_USER_SUCCESS = 'LOGOUT_FIREBASE_USER_SUCCESS';
export const LOGOUT_FIREBASE_USER_FAILURE = 'LOGOUT_FIREBASE_USER_FAILURE';

export const LOGIN_FIREBASE_USER_SUCCESS = 'LOGIN_FIREBASE_USER_SUCCESS';
export const LOGIN_FIREBASE_USER_FAILURE = 'LOGIN_FIREBASE_USER_FAILURE';